
const MAX_HASHTAGS_AMOUNT = 5;
const SCALE_STEP = 25;
const MIN_SCALE = 25;
const MAX_SCALE = 100;
const MIN_COMMENT_LENGTH = 0;
const MAX_COMMENT_LENGTH = 140;
const ALERT_SHOW_TIME = 5000;

export { MAX_HASHTAGS_AMOUNT, SCALE_STEP, MIN_SCALE, MAX_SCALE, MIN_COMMENT_LENGTH, MAX_COMMENT_LENGTH, ALERT_SHOW_TIME };
